name: Deploy to Prod

on:
  push:
    branches: 
      - main
    paths-ignore:
    - '*.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
    - '*.md'
jobs:
  deploy_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:prod
    - name: stop and remote old container
      run: |
        docker stop discord_bot_live
        docker rm discord_bot_live
      continue-on-error: true
    - name: List images
      run: docker image ls
    - name: Run the Docker image
      run: docker run -d -e $discord_bot_token --name discord_bot_live discord_bot:prod 
      env:
        discord_bot_token: ${{ secrets.prod_discord_bot_token }}
